export type BuiltinSkillId = 'clean-note' | 'split-note' | 'map-vault' | 'create-skill' | 'analyze' | 'graph-connect' | 'canvas-builder' | 'ask-vault';

export interface BuiltinSkill {
  id: BuiltinSkillId;
  slash: `/${BuiltinSkillId}`;
  name: string;
  hint: string;
  description: string;
  buildPrompt: (request: string) => string;
}

const COMMON_OBSIDIAN_RULES = [
  'You are running inside AgyObsidian, an Obsidian-native Antigravity workflow.',
  'Use Obsidian Flavored Markdown: wikilinks, embeds, callouts, frontmatter, tags, and MOC sections when useful.',
  'Prefer current note and selected text. Use pinned notes only as supporting context.',
  'Do not scan the whole vault unless this skill explicitly asks for vault/folder mapping.',
  'If editing files, keep changes small, reversible, and explain exactly which notes changed.',
  'Never delete user content. Move or summarize content only when preserving a backlink to the source.',
].join('\n');

function withOptionalRequest(request: string): string {
  return request.trim()
    ? `\n\nAdditional user direction:\n${request.trim()}`
    : '';
}

export const BUILTIN_SKILLS: BuiltinSkill[] = [
  {
    id: 'clean-note',
    slash: '/clean-note',
    name: '노트 정리',
    hint: '노트 구조 및 서식 정리',
    description: '현재 노트의 제목, 메타데이터, 태그, 중복 내용 등을 깔끔하게 정제합니다.',
    buildPrompt: (request) => [
      COMMON_OBSIDIAN_RULES,
      '',
      '# Built-in Skill: Note Surgeon',
      '',
      'Goal: improve the active Obsidian note so it becomes easier to read, link, revisit, and reuse.',
      '',
      'Workflow:',
      '1. Diagnose the note structure: title, frontmatter, headings, duplicated sections, missing links, weak tags, and unclear claims.',
      '2. Produce a concise surgery plan before any file edit.',
      '3. If safe file editing is available, update only the active note. If editing is not available, output a patch-style replacement section.',
      '4. Preserve original meaning and important details. Do not shorten aggressively unless the user asks.',
      '',
      'Expected output:',
      '- Changed sections',
      '- Added or improved frontmatter/tags',
      '- Suggested wikilinks',
      '- Any extracted-note candidates',
      '- Verification that the note still reads coherently',
      withOptionalRequest(request),
    ].join('\n'),
  },
  {
    id: 'split-note',
    slash: '/split-note',
    name: '나노 노트 분할기',
    hint: '긴 노트를 여러 개의 나노 노트로 분할',
    description: '내용이 긴 노트를 여러 개의 독립적인 나노 노트로 쪼개고 원본 노트에 백링크를 남깁니다.',
    buildPrompt: (request) => [
      COMMON_OBSIDIAN_RULES,
      '',
      '# Built-in Skill: Nano Note Splitter',
      '',
      'Goal: split the active note into small, self-contained nano notes that can be reused across the vault.',
      '',
      'Nano note criteria:',
      '- One durable idea, claim, concept, person, company, source, question, or action per note.',
      '- A clear title that can stand alone as a wikilink.',
      '- A backlink to the source note.',
      '- Minimal but useful context, not a blind copy of the original.',
      '',
      'Workflow:',
      '1. Identify 3-12 nano note candidates from the active note or selected text.',
      '2. For each candidate, propose title, reason, destination filename, tags, and backlink structure.',
      '3. If safe file editing is available, create the new notes and update the source note with an "Nano notes" section linking them.',
      '4. If editing is not available, output exact markdown blocks for each new note and the source-note insertion.',
      '',
      'Output format:',
      '## Nano split result',
      '- Created or proposed notes',
      '- Source note update',
      '- Link map',
      '- Follow-up notes worth creating later',
      withOptionalRequest(request),
    ].join('\n'),
  },
  {
    id: 'map-vault',
    slash: '/map-vault',
    name: '볼트 지도 생성기',
    hint: '연관 노트 탐색 및 클러스터링',
    description: '현재 노트 주변의 연관된 노트들을 탐색하여 클러스터링하고 MOC(지식 지도)를 만들어줍니다.',
    buildPrompt: (request) => [
      COMMON_OBSIDIAN_RULES,
      '',
      '# Built-in Skill: Vault Cartographer',
      '',
      'Goal: make a useful map of the current note neighborhood, not a decorative graph.',
      '',
      'Scope rules:',
      '- Default scope: active note, linked notes, backlinks if cheaply available, pinned notes, and the active note folder.',
      '- If the user names a folder, map only that folder.',
      '- Avoid full-vault scans unless the user explicitly asks for "whole vault" or "entire vault".',
      '',
      'Analyze:',
      '- Hub notes and isolated notes',
      '- Concept clusters',
      '- Missing links between related notes',
      '- MOC candidates',
      '- Duplicate or overlapping notes',
      '- Stale notes that may need review',
      '',
      'Expected output:',
      '1. A short map summary',
      '2. Cluster list',
      '3. Recommended links to add',
      '4. MOC note proposal',
      '5. Optional Mermaid graph for quick preview',
      '6. Optional JSON node-edge sketch for future 3D graph rendering',
      '',
      'If safe file editing is available and the user asks to apply, create or update only a map/MOC note. Do not mass-edit the vault.',
      withOptionalRequest(request),
    ].join('\n'),
  },
  {
    id: 'create-skill',
    slash: '/create-skill',
    name: 'AgyObsidian 스킬 생성기',
    hint: '나만의 옵시디언 스킬 제작',
    description: '사용자의 워크플로우를 분석하여 옵시디언에서 바로 쓸 수 있는 새로운 슬래시 스킬을 만들어줍니다.',
    buildPrompt: (request) => [
      COMMON_OBSIDIAN_RULES,
      '',
      '# Built-in Skill: AgyObsidian Skill Forge',
      '',
      'Goal: turn the user\'s workflow idea into a reusable AgyObsidian Obsidian-native slash skill.',
      '',
      'The created skill should feel native to Obsidian, not like a generic prompt. It should understand active notes, selected text, pinned notes, wikilinks, frontmatter, tags, embeds, note creation, and safe note editing.',
      '',
      'Workflow:',
      '1. Infer the intended workflow from the user request and active note context.',
      '2. If the request is underspecified, make a reasonable first version and list assumptions instead of asking many questions.',
      '3. Design the skill contract: slash name, purpose, activation examples, input context, output files/sections, mutation policy, safety rules, and verification steps.',
      '4. Produce a ready-to-save markdown skill definition for AgyObsidian.',
      '5. If safe file editing is available and the user explicitly asked to create/install the skill, write it under `.agy-obsidian/skills/<skill-id>/SKILL.md`; otherwise output the file content and install steps.',
      '',
      'Skill file format to generate:',
      '---',
      'name: <kebab-case-skill-name>',
      'slash: /<kebab-case-skill-name>',
      'description: <one sentence>',
      'inputs:',
      '  activeNote: true|false',
      '  selectedText: true|false',
      '  pinnedNotes: true|false',
      '  folderScope: optional|required|none',
      'mutationPolicy: preview-first|apply-when-explicit|read-only',
      '---',
      '',
      '# <Skill Name>',
      '',
      '## Purpose',
      '## When To Use',
      '## Inputs',
      '## Workflow',
      '## Output Contract',
      '## Safety Rules',
      '## Verification',
      '## Example Invocations',
      '',
      'Output format:',
      '## Skill Forge Result',
      '- Slash command',
      '- What it does',
      '- Files to create',
      '- Generated SKILL.md',
      '- Test prompts',
      '- Upgrade path using Antigravity SDK if the skill needs programmatic tools',
      withOptionalRequest(request),
    ].join('\n'),
  },
  {
    id: 'analyze',
    slash: '/analyze',
    name: '심층 분석 랩 (Sukgo)',
    hint: '다각도 심층 분석 및 의사결정',
    description: '제1원리, 5 Whys, 악마의 대변인 등 다양한 사고 프레임워크를 적용하여 현재 노트를 심층 분석합니다.',
    buildPrompt: (request) => [
      COMMON_OBSIDIAN_RULES,
      '',
      '# Built-in Skill: Sukgo Decision Lab',
      '',
      'Goal: help the user think better about a decision, plan, claim, investment, career move, education question, or strategy using sukgo-style thinking frameworks.',
      '',
      'Context:',
      '- The original sukgo project is a Korean decision-making CLI. This AgyObsidian skill ports its core thinking workflow into an Obsidian-native Antigravity skill.',
      '- Use the active note, selected text, and pinned notes as the decision context.',
      '- Do not require the separate sukgo CLI unless the user explicitly asks for CLI execution.',
      '',
      'Framework menu:',
      '- steelman: strongest opposing argument',
      '- devil: adversarial critique',
      '- premortem: failure simulation',
      '- 6hats: six thinking hats',
      '- inversion: reverse thinking',
      '- 5whys: root cause analysis',
      '- matrix: weighted decision matrix',
      '- first-principles: reduce to fundamentals',
      '- ooda: observe-orient-decide-act',
      '- toulmin: claim, grounds, warrant, backing, rebuttal',
      '- compare: use 3-5 relevant frameworks and synthesize',
      '',
      'Routing rules:',
      '1. If the request names a framework, use that framework.',
      '2. If no framework is named, choose compare mode with 3 frameworks that best fit the active note.',
      '3. For investment notes, include risk, thesis, counter-thesis, catalysts, and decision triggers.',
      '4. For career or education notes, include values, constraints, stakeholders, and next experiments.',
      '5. Be direct and concrete. The output should sharpen the user\'s decision, not merely summarize the note.',
      '',
      'Output format:',
      '## Sukgo Decision Lab',
      '- Decision or question being analyzed',
      '- Frameworks used',
      '',
      '## Analysis',
      '- Use clear Korean headings for each selected framework.',
      '',
      '## Decision Synthesis',
      '- Best current answer',
      '- Strongest counterargument',
      '- Unknowns that matter',
      '- 3 next actions',
      '',
      '## Obsidian Follow-up',
      '- Suggested wikilinks',
      '- Atomic notes worth creating',
      '- Optional tags/frontmatter improvements',
      '',
      'If safe editing is available and the user explicitly asks to save/apply, create a concise decision note in `000-Inbox` or update only the active note with a "Sukgo analysis" section.',
      withOptionalRequest(request),
    ].join('\n'),
  },
  {
    id: 'graph-connect',
    slash: '/graph-connect',
    name: '자동 그래프 연결기',
    hint: '누락된 링크 자동 찾기',
    description: '내 볼트 내에서 연결고리가 부족한 노트를 찾아, 문맥상 어울리는 다른 노트와의 [[내부 링크]]를 자동으로 제안합니다.',
    buildPrompt: (request) => [
      COMMON_OBSIDIAN_RULES,
      '',
      '# Built-in Skill: Auto Graph Linker',
      '',
      'Goal: Integrate the active note naturally into the Obsidian Graph View by creating [[internal links]] to related existing notes.',
      '',
      'Workflow:',
      '1. Extract key concepts, themes, people, projects, and entities from the active note.',
      '2. Use your workspace access to search the vault for existing notes that match or relate deeply to these concepts.',
      '3. If safe file editing is available:',
      '   a) Replace matching text within the active note with [[Note Title]] wikilinks.',
      '   b) If direct inline linking is awkward, append a "## Related Notes" section at the bottom of the note with bulleted links.',
      '4. Aim to establish at least 2-4 meaningful connections so this note is no longer an orphan in the Graph View.',
      '5. Output a brief summary of the links you added and why they are relevant.',
      withOptionalRequest(request),
    ].join('\n'),
  },
  {
    id: 'canvas-builder',
    slash: '/canvas-builder',
    name: '캔버스 AI 빌더',
    hint: '마인드맵 및 캔버스 자동 생성',
    description: '작성 중인 텍스트 노트를 시각적 구조를 갖춘 옵시디언 캔버스(.canvas) 파일로 즉시 변환해줍니다.',
    buildPrompt: (request) => [
      COMMON_OBSIDIAN_RULES,
      '',
      '# Built-in Skill: Canvas Builder',
      '',
      'Goal: Translate the user\'s prompt or the active text into an Obsidian Canvas file (.canvas).',
      '',
      'Obsidian Canvas JSON schema overview:',
      '- A canvas is a JSON object with `nodes` and `edges` arrays.',
      '- Nodes represent cards or files. Structure: `{"id":"unique-id","type":"text","text":"Content","x":0,"y":0,"width":250,"height":100}`.',
      '- Edges connect nodes. Structure: `{"id":"edge-id","fromNode":"node-id-1","fromSide":"bottom","toNode":"node-id-2","toSide":"top"}`.',
      '',
      'Workflow:',
      '1. Analyze the active note or the user request to extract a hierarchical structure or flowchart.',
      '2. Map the items into nodes with reasonable x/y coordinates to form a clear visual layout (e.g., top-down or left-to-right).',
      '3. Create edges to connect related nodes.',
      '4. Output the raw `.canvas` JSON structure.',
      '5. If safe file editing is available, use your workspace tools to write the generated JSON to a new `.canvas` file in the vault (e.g., `Generated-Canvas.canvas`).',
      '',
      'Output format:',
      '- Summary of the generated visual structure.',
      '- Target filename and saved location.',
      '- The raw `.canvas` JSON inside a `json` code block (as a fallback).',
      withOptionalRequest(request),
    ].join('\n'),
  },
  {
    id: 'ask-vault',
    slash: '/ask-vault',
    name: '볼트 전체 질문 (RAG)',
    hint: '내 볼트 전체를 대상으로 질문',
    description: '무거운 벡터 DB 없이 로컬 환경에서 옵시디언 볼트 전체를 스캔하고 질문에 대한 답변을 찾습니다.',
    buildPrompt: (request) => [
      COMMON_OBSIDIAN_RULES,
      '',
      '# Built-in Skill: Vault Q&A (RAG)',
      '',
      'Goal: Act as a Retrieval-Augmented Generation (RAG) agent to answer the user\'s question by searching their entire knowledge base.',
      '',
      'Workflow:',
      '1. Parse the user\'s question to identify key concepts and search terms.',
      '2. Using your innate workspace search capabilities (like grep, file reading, or semantic search), scan the vault to find relevant notes.',
      '3. Do not just rely on the active note. The purpose of this skill is to look across the entire vault.',
      '4. Synthesize the findings into a comprehensive answer.',
      '5. Explicitly cite the sources of your information using Obsidian wikilinks (e.g., [[Note Title]]) so the user can verify the information.',
      '',
      'Output format:',
      '- A direct answer to the user\'s question.',
      '- "Sources" or "References" section with bullet points of linked notes.',
      withOptionalRequest(request),
    ].join('\n'),
  },
];

export function getBuiltinSkillBySlash(prompt: string): { skill: BuiltinSkill; request: string } | null {
  const match = prompt.match(/^\/(clean-note|split-note|map-vault|create-skill|analyze|graph-connect|canvas-builder|ask-vault)(?:\s+([\s\S]+))?$/);
  if (!match) return null;
  const skill = BUILTIN_SKILLS.find((item) => item.id === match[1]);
  if (!skill) return null;
  return {
    skill,
    request: (match[2] || '').trim(),
  };
}
